### ISSUE TITLE
[joss-reviews#2974] Class design regarding Moead and Problems

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#17]
Related: openjournals/joss-reviews#2974

`Moead` and `Problem` classes require files, but I cannot see their definition somewhere documented. 

A better option could be to work directly with data structures. (arrays, lists, dicts)
Helper functions could be created in order to avoid the clutter of loading these.

**Comment by geoffreyp** [comment]
Hello, the documentation is updated to explain how to use and generate these files.
I explain the utility of instance files for problems in #16.

We choose to externalize the weight-vector component by using files because there are many ways to generate weight vectors for multi-objective optimization by decomposition and this way allow the researcher to use the same weight-vectors with different algorithms/framework. We provide some example files with the framework: https://github.com/moead-framework/data/blob/master/weights

**Comment by chkoar** [comment]
Let'w keep only the #16
